version: "3"
services:
  
  client:
    build:
        context: ./client
        dockerfile: Dockerfile
    ports:
      -  3000:3000
    container_name: booking-app-client
    networks:
      -  booking-app-stack-net
    volumes:
      -  ./client/src:/usr/app/src
      -  ./client/public:/usr/app/public
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    build:
        context: ./api
        dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: booking-app-api
    networks:
      - booking-app-stack-net
    volumes:
      - ./api/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - booking-app-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  booking-app-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local